name: esigen-pymol
channels:
  - omnia
  - egilliesix
dependencies:
  - python=2.7
  - nomkl
  - pymol
  - numpy
  - libglu
  - pip:
    - apscheduler
    - cclib
    - flask
    - flask-sslify
    - markdown
    - gunicorn
    - requests